services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-}
        TARGETPLATFORM: ${TARGETPLATFORM:-}

    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mcr.microsoft.com/azure-sql-edge
    platform: ${DB_PLATFORM:-linux/amd64}
    hostname: SQL-Library
    container_name: SQL-Library
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    # Add "forwardPorts": ["1433"] to **devcontainer.json** to forward MSSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    platform: ${AZURITE_PLATFORM:-linux/amd64}
    hostname: azurite
    container_name: azurite
    restart: unless-stopped
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service  
      - "10002:10002"  # Table service
    volumes:
      - azurite-data:/data
    # Add "forwardPorts": ["10000", "10001", "10002"] to **devcontainer.json** to forward Azurite locally.

volumes:
  azurite-data: