name: Build and Push Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name (lowercase)
        id: set-image-name
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}/app:latest"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.set-image-name.outputs.image_name }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.set-image-name.outputs.image_name }}
