name: Build and Push Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name (lowercase)
        id: set-image-name
        run: |
          REPO_NAME=${GITHUB_REPOSITORY,,}
          echo "base_repo=ghcr.io/$REPO_NAME" >> $GITHUB_OUTPUT
          echo "app_image=ghcr.io/$REPO_NAME/app:latest" >> $GITHUB_OUTPUT

      - name: Build Docker Compose services
        run: |
          docker compose build

      - name: Tag and Push app service
        run: |
          docker tag my-basic-container-app:latest ${{ steps.set-image-name.outputs.app_image }}
          docker push ${{ steps.set-image-name.outputs.app_image }}
